#ddev-gitpod-generated
router_http_port: 8080
router_https_port: 8443
use_dns_when_possible: false

additional_fqdns:
- 8080-yetsabeth-drupaltaller-aazow3wm70g.ws-us106.gitpod.io
- 8025-yetsabeth-drupaltaller-aazow3wm70g.ws-us106.gitpod.io
- 8036-yetsabeth-drupaltaller-aazow3wm70g.ws-us106.gitpod.io
